using System;

namespace TryCatchFinallyErrors
{
    class Program
    {
        static void Main(string[] args)
        {
            //try
            //{
            //    Console.WriteLine("Enter a number");
            //    int number = Convert.ToInt32(Console.ReadLine());
            //    Console.WriteLine("Number : " + number);
            //}
            //catch (Exception ex)
            //{

            //    Console.WriteLine("Error : " + ex.Message.ToString());
            //}
            //finally
            //{
            //    Console.WriteLine("Process completed. ");
            //}

            try
            {
                //int a = int.Parse(null);
                //int b = int.Parse("test");
                int c = int.Parse("-32532523663634");
            }
            catch (ArgumentNullException ex)
            {

                Console.WriteLine("Null parameter.");
                Console.WriteLine(ex);
            }
            catch(FormatException ex)
            {
                Console.WriteLine("Parameter not correct");
                Console.WriteLine(ex);
            }

            catch (OverflowException ex)
            {
                Console.WriteLine("Too slow or too big parameter");
                Console.WriteLine(ex);
            }


        }
    }
}
